### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by Matael** [haum/haum_internal#2]
Ce serait cool de commencer à chiffrer un budget un peu propre pour le HAUM. Combien on a besoin par an pour faire tourner la structure de l'asso seule, comment on finance les projets.

On est au moins deux à penser qu'a terme, le HAUM ne devra pas dépendre du serveur d'un membre ou de la présence d'un membre. A nous de faire en sorte que ce HS soit *vraiment* horizontal.

**Comment by MicroJoe** [comment]
Cette prévision de budget datant de 2014, je me permet de fermer cette issue (surtout que l'on a augmenté la cotisation en 2015).
