### ISSUE TITLE
Revoir les photos sur le compte Twitter

### ISSUE THREAD

**Issue by MicroJoe** [haum/haum_internal#34]
On avait parlé sur IRC du problème de la photo de bannière qui était étirée et l'image de profil qui ne possède que le A du HAUM.

Pour la bannière, réfléchir à corriger le problème d'étirement en rajoutant des bandes blanches sur le côté ou le rendre plus vivant en ajoutant des photos de projets.

Pour l'image de profil afficher uniquement le A est peut-être voulu ou alors c'est mon Firefox qui déconne.

Ajout : dans la description mettre le AU en majuscules pour refléter l'acronyme ?

**Comment by fredblain** [comment]
Salut,
x Pour la bannière du compte, on avait effectivement discuté de mettre une autre photo qui illustrerait davantage l'asso (photo(s) de projet(s) plus que une photo de membres d'ailleurs), à voir laquelle/lesquelles.
x Pour l'image de profile, ça illustre le côté bidouille avec la LED, je ne trouve pas personnellement que ça soit choquant et non, ce n'est pas ton Ffx qui merde @MicroJoe ;). On peut mettre autre chose, à voir quoi.
x Pour le "AU" dans le descriptif du profile, j'ai essayé pour voir, et ça m'a davantage donné l'impression d'un acronyme qu'autre chose.. sur le site ça passe parce que les couleurs aident à mettre l'acronyme du HAUM en exergue, mais là... après ce n'est qu'un avis personnel, si d'autres avis vont dans ce sens, on pourra changer ça :)

**Comment by fredblain** [comment]
Du nouveau là-dessus @MicroJoe ?
Tu as des propositions par rapport à ce qu'il y a sur le Flickr actuellement ?

**Comment by MicroJoe** [comment]
Pas encore. J'essaierai de faire des maquettes sous GIMP et de les mettre ici pour enlever ce problème de pixelisation et éventuellement mettre des photos dans la bannière à partir du Flickr.

**Comment by MicroJoe** [comment]
Peut-on considérer cette demande comme résolue ? Les sources XCF sont toujours disponibles si il y a des modifications à faire mais c'est déjà beaucoup mieux qu'avant à mon avis.

**Comment by Matael** [comment]
Ça me convient aussi, let's close this :)
