### ISSUE TITLE
Problème de gestion des droits sur le mailman

### ISSUE THREAD

**Issue by MicroJoe** [haum/haum_internal#35]
Je viens de voir que l'accès aux archives de haum_hackerspace était bien sécurisé par mot de passe et donc accessible uniquement aux membres mais par contre la liste bureau_haum qui me semble plus sensible n'est elle pas du tout protégée.

Je ne sais pas si c'est très cool de le mettre ici car ça pourrait être une sorte de faille mais que ce soit ici ou sur l'IRC il faut que ça se sache pour être corrigé rapidement au besoin.

**Comment by jblb** [comment]
fixed ! 
Merci MicroJoe d'avoir fouillé de ce cote là
