### ISSUE TITLE
Visuel/Flyer de communication pour le HAUM

### ISSUE THREAD

**Issue by fredblain** [haum/haum_internal#36]
Proposition de @JackDesBwa : écrire un visuel/créer un logo pour les Jeudis du libre (renforcer notre visibilité sur les canaux de l'Epicerie du Pré). J'appuie cette idée.

Pour ma part, je propose également la création d'un flyer pour renforcer la communication globale du HAUM.
Exemple de flyer communautaire (MozFR) dont on pourrait s'inspirer :  https://github.com/AmarOk1412/Flyer-MozFr

**Comment by MicroJoe** [comment]
Que fait-on de cette issue étant donné que les pochettes ont plutôt bien fonctionné de ce que j'ai entendu à Nantes et qu'elles sont bien plus classes que de banals flyers ?

**Comment by neomilium** [comment]
Les pochettes correspondent bien à la demande : c'est un support flexible et qui plaît bien.
