### ISSUE TITLE
Coussin ouvreur

### ISSUE THREAD

**Issue by JackDesBwa** [haum/haum_internal#37]
Le HAUM devrait se munir d'un coussin pour l'ouverture de la porte d'entrée (lorsque le bâtiment est fermé au public). Le fonctionnement va comme suit :

**Étape 1:**
Le membre (A), présent au lab, vérifie depuis l'étage l'identité et la disponibilité de la personne (B) voulant entrer.
**Étape 2:**
Le membre (A) lance le coussin ouvreur qui tombe devant le détecteur
**Étape 3.1:**
Si la visée est bonne, (B) peut entrer et remonte le coussin
**Étape 3.2:**
Si la visée est mauvaise, (A) descend chercher le coussin

**Facultatif:**
Dans le cas 3.2, (A) peut remonter pour faire un nouvel essai.

Idée originale de @jblb patchée par @jackdesbwa

**Comment by fredblain** [comment]
S'il te plaît @AliDi, tu voudrais pas nous faire un zoli coussin par hasard ? :)

**Comment by AliDi** [comment]
Sachant maintenant faire un panda, je pourrais peut-être faire un coussin dans ce goût là (écureuil volant) : http://www.photodenature.fr/ecureuil-volant/photo-ecureuil-volant-4/

**Comment by fredblain** [comment]
Ben écoute, moi cette idée me plaît beaucoup !

**Comment by sebvallee** [comment]
Est ce que cette issue n'est pas résolu depuis un petit moment ? ping @Matael ?

**Comment by matael** [comment]
De fait, l'ouverture est assurée désormais de manière (quasi)automatique. Je ferme l'issue.
