### ISSUE TITLE
Ouvrir un accès depuis l'exterieur vers Carbon

### ISSUE THREAD

**Issue by neomilium** [haum/haum_internal#38]

**Comment by neomilium** [comment]
Un SSH est déjà ouvert.

**Comment by neomilium** [comment]
Je m'occupe du reverse-proxy sur notre routeur

**Comment by rebrec** [comment]
Vous aviez pas évoqué le fait de migrer le routeur existant vers une SFRBox ? (désolé je suis ptet en retard)

**Comment by neomilium** [comment]
Oula, il faut relire le mail :)


2015-03-26 14:13 GMT+01:00 rebrec <notifications@github.com>:

**Comment by neomilium** [comment]
De quel routeur existant tu parles ?

**Comment by rebrec** [comment]
J'ai lu un mail évoquant un routeur "Soekris" qui si j'ai bien compris devais être migré vers une NeufBox ou SFRBox

**Comment by neomilium** [comment]
Il évoque un Soekris, oui... qui n'est donc pas "existant", par contre la
NeufBox l'est :) (depuis des mois maintenant :))

**Comment by rebrec** [comment]
Autre question : pour l'accès SSH qui peut y accéder ? j'aurais été intéressé pour une autre Issue qui parle de migrer la ML mais du coup me j'intérroge...de même est-ce qu'on met les services dans des chroot, des containers ? rien de tout ca ? etc... mais je suis pas un habitué de github alors je devrais ptet parler de ca autre part ?

**Comment by rebrec** [comment]
ok --> [ ]

**Comment by neomilium** [comment]
Pour SSH, c'est simple : les gens qui ont un accès, y ont accès, pas mal,
non ?
Nominativement : mathieu, jérome, florent et moi-même (les gens qui étaient
présents lors de l'install du serveur et ceux qui en ont demandé un -
poliment et physiquement, histoire qu'ils tapent leur mot de passe)
Ceci dit, il serait judicieux de clore l'accès par mdp prochainement.

Pour les autres questions, c'est toujours la même chose au Haum : pas de
règle verticale mais une gestion horizontale...

2015-03-26 14:28 GMT+01:00 rebrec <notifications@github.com>:

**Comment by jblb** [comment]
Romuald Conty <notifications@github.com> a écrit :

> Ceci dit, il serait judicieux de clore l'accès par mdp prochainement.
pour moi c'est bon on peu clore, mais je ne sais pas si c'est faisable  
"par user"

-- 
@+
jérôme

**Comment by jblb** [comment]
Romuald Conty <notifications@github.com> a écrit :

> Pour SSH, c'est simple : les gens qui ont un accès, y ont accès, pas mal,
> non ?
> Nominativement : mathieu, jérome, florent et moi-même (les gens qui étaient
> présents lors de l'install du serveur et ceux qui en ont demandé un -
> poliment et physiquement, histoire qu'ils tapent leur mot de passe)

feedoo m'en a demandé un par irc je fait quoi ?

-- 
@+
jérôme

**Comment by rebrec** [comment]
jblb : tu peux utiliser la directive Match dans le sshd_config apres tu peux jouer par user ou group et désactiver l'authent par mdp.

Si je balance par mail ma pubkey quelqu'un peut me créer un compte ?
Je suppose que vous donner un accès sudo pour que chacun puisse installer des choses ou pas ?

**Comment by neomilium** [comment]
L'accès par mdp est fermé pour tous, il faut passer par une clef publique.
Par mail, c'est ok.

Concernant, l'administration partagée : on fait des choses de manière
concertée... pas d'anarchie :) et on documente TOUTES ces opérations.

**Comment by rebrec** [comment]
ca paraît logique mais ca veut dire quoi ? que qq'1 effectuera les manip nécessittant des privileges élevés ? ou qu'on reste autonome et resposnable ?

**Comment by neomilium** [comment]
Je n'arrive pas à mes fins avec tinyproxy sur la neufbox, je reprendrai l'issue plus tard.

**Comment by neomilium** [comment]
C'est fait avec lighttpd :)
