### ISSUE TITLE
Mettre à jour la cotisation sur HackerspaceWiki

### ISSUE THREAD

**Issue by MicroJoe** [haum/haum_internal#41]
J'ai trouvé cette page en me promennant : https://wiki.hackerspaces.org/HAUM

La cotisation n'est pas à jour (on est passé à 20 €) et le point sur la carte a l'air bizarrement placé, au niveau d'une rue au lieu du bâtiment. Il faudrait également mettre à jour l'adresse pour mettre celle complète que l'on donne sur le site.

Je n'ai pas de compte sur ce Wiki mais je pense que ça ne devrait pas trop prendre de temps à mettre à jour pour celui qui a créé ce noeud.

EDIT : on peut carrément s'inspirer ce [cette présentation du PCMlab](https://wiki.hackerspaces.org/PMClab) pour fournir plus de métadata aux éventuels intéressés et faire deux descriptions anglaises/françaises.

**Comment by fredblain** [comment]
Merci @MicroJoe pour ta suvreillance.
Il me semble que c'est @Matael qui avait créé l'entrée du HAUM sur ce wiki. Je vais voir avec lui.

**Comment by Matael** [comment]
C'est fait. J'en ai profité pour commencer une liste des machines/outils dispos là bas et rajouter un lien vers spaceapi.net
