### ISSUE TITLE
Rendre visible les articles

### ISSUE THREAD

**Issue by neomilium** [haum/haum_internal#42]

**Comment by Matael** [comment]
Effectivement, les articles sont tout en bas... ce qui est pas top.

Reste à voir ce que l'on pourrait faire : deux colonnes  ? J'ai peur que ce soit moche...

**Comment by sebvallee** [comment]
Avec le nouveau design du site, ce "problème" semble résolu... Je ferme.

**Comment by jblb** [comment]
résolu si il n'y a pas trop de «Prochains événements»
une solution serait peut être ne n'afficher que LE prochain événements

**Comment by sebvallee** [comment]
Ou pas... les évènements sont ce qui fait "vivre" l'asso, n'en afficher qu'un, c'est montrer qu'on ne vit que peu...

**Comment by jblb** [comment]
en afficher qu'un seul mais expliquer clairement que les autres ne sont pas là
ps: réflexion en direct qui peut être complètement nulle

**Comment by fredblain** [comment]
tous les futurs evenements ne sont pas affiches, mais seuls les 4 (ou 5) prochains dans le calendrier.

**Comment by jblb** [comment]
donc n'en mettre qu'un avec un liens vers la page agenda n'est pas forcement si stupide que ça

**Comment by fredblain** [comment]
@jblb non, ce n'est pas ce que j'ai dit. j'appuie la reponse de @sebvallee sur le fait qu'il faut montrer qu'on a plusieurs evenement en cours, seulement on a pas besoin d'afficher toute les sessions du mois en cours sans quoi un evenement la semaine suivante (et qui n'est pas une ouverture du local) peut se trouver noye dans la masse.
N'afficher que les 4 ou 5 prochains evenements permet de se concentrer sur un calendrier a court terme.
Pour ce qui est d'un lien vers la page agenda, il existe deja: "Vous pouvez **importer notre agenda** pour être automatiquement informé(e) de nos évènements, ou simplement le **consulter en ligne**."

**Comment by jblb** [comment]
@fredblain «un» peut être deux ou trois, l'idée c'est que la casse  «Prochains événements» ne soit pas trop haute et laisse apparaître les articles

**Comment by fredblain** [comment]
un compromis pourrait etre de modifier l'affichage (a commencer par la date) des evenements pour reduire la voilure du panneau agenda sur la page d'accueil.

**Comment by matael** [comment]
On pourrait aussi remplacer la ligne "Vous pouvez importer notre agenda pour être automatiquement informé(e) de nos évènements, ou simplement le consulter en ligne." par deux boutons "Tous les évènements"  & "Importer l'agenda du HAUM". On réduirait ainsi l'impression de texte et on pourrait revoir les sections Planet & Blog pour que les listes soient plus sexy.

**Comment by sebvallee** [comment]
@Matael Je vote pour !

**Comment by fredblain** [comment]
@Matael, @sebvallee, @jblb : tant qu'on ne reduit pas l'affichage des prochains evenements a un seul, je suis pour. 
A voir aussi ce que donnerait une section "proch. events" refondue a droite, au dessus du zoom sur les projets. Le fil twitter serait un peu plus bas encore, mais pour le coup je ne pense pas que ce soit genant.

**Comment by jblb** [comment]
j'aime bien l'idée de @Matael

**Comment by matael** [comment]
Un avis sur un truc comme ça ? 
![exemple](https://cloud.githubusercontent.com/assets/907720/19620447/df3f24fa-987d-11e6-8cab-9b2e2eccad78.png)

**Comment by jblb** [comment]
yes, avec la reduction de la taille de la date comme disais @fredblain

**Comment by matael** [comment]
This way ?
![exemple2](https://cloud.githubusercontent.com/assets/907720/19620543/2a9a0742-9880-11e6-9491-211a681923c9.png)

**Comment by jblb** [comment]
moi ça me va

**Comment by sebvallee** [comment]
I'm in
