### ISSUE TITLE
Lister le matériel recherché

### ISSUE THREAD

**Issue by neomilium** [haum/haum_internal#43]
Le hacklab manque de tout et parfois de chose précise à court terme, on pourrait invité au don de matériel plus facilement si on listait nos besoins.

**Comment by MicroJoe** [comment]
QUID de faire une page sur le Wiki ? Je veux bien m'en charger si ça suffit comme support.

**Comment by MicroJoe** [comment]
https://wiki.haum.org/doku.php?id=materiel_local
