### ISSUE TITLE
Fermer les bugtrackers des autres projets

### ISSUE THREAD

**Issue by MicroJoe** [haum/haum_internal#47]
Les plus attentifs d'entre vous auront remarqué que j'ai déplacé (manuellement) les issues de AxiHAUM de ce bugtracker vers celui du projet (ping @neomilium). Cependant, nous venons d'avoir une discussion sur IRC avec @fredblain et il faudrait éviter de répartir un peu partout les issues des projets mais les concentrer sur ce bugtracker uniquement pour faciliter la contribution des membres en jetant un unique coup d'oeuil à la liste des choses à faire, tous projets confondus.

Ce ticket est ouvert à la discussion. Si ce concept de tout regrouper est validé, il faudra alors supprimer les issues que j'ai créé sur AxiHAUM, les remettre ici, et supprimer tous les bugtrackers de tous les autres projets du HAUM si Github le permet afin d'éviter les erreurs de déclaration de tickets dans le mauvais bugtracker.

EDIT : Il est effectivement possible de supprimer le bugtracker d'un projet dans les options Github du projet.

**Comment by fredblain** [comment]
Pour completer @MicroJoe, je reprends ici ce que j'ai pu dire sur le sujet sur IRC :
Je trouve plus simple de dire a un nouveau membre: "soit le bienvenue, jete un oeil a haum_internal si tu veux contribuer pour voir les differents projets en cours, regarder s'il y a des choses que tu peux/veux faire et si jamais tu veux commencer facile, certains projets ont des issues "easy" pour aider a se lancer.", plutot que d'avoir a lui dire de jeter un oeil a TOUS les trackers de TOUS les depots pour savoir s'il peut contribuer a quelque chose.
Autre avantage selon moi de concentrer les issues sur un seul et meme tracker pour une asso comme le HAUM: pouvoire faire plus facilement le tours des issues encore ouvertes pour relancer les plus anciennes plutot que d'avoir a faire le tour de tous les depots, en ayant au prealable fait le tri entre les projets (en cours, fini, avortes, etc.). 
De plus, nous avons mis en place des github hooks pour monitorer les activites des depots principaux du HAUM, et notamment haum_internal. Je pense donc qu'il est plus simple de continuer a gerer les issues des differents projets ici (d'autant plus que ce depot a ete cree expressement pour ca) plutot que d'avoir a mettre en place des hooks sur tous les nouveaux depots, etc.

**Comment by Matael** [comment]
Mon coeur irait plus vers la répartition des bugs dans les trackers des projets liés. Cela me semble plus propre ainsi. Je me suis toutefois penché sur cette migration vendredi dernier et je n'ai rien fait parce queje partage un peu la vision que proposent @fredblain et @MicroJoe .

Je pense que pour prendre en main les projets, c'est plus simple ainsi, même si , d'un point de vue purement pratique, Github propose une page de récap de *toutes* les issues ouvertes (voir l'onglet Issues en haut de page)

**Comment by fredblain** [comment]
@Matael: aussi loin que je me souvienne, l'idee de tout rassembler dans un seul et meme tracker venait de toi. J'ai simplement repris ici les motivations de ce choix.
Maintenant s'il vous est plus pratique de vous organiser autrement, faites :)

**Comment by MicroJoe** [comment]
J'étais également du même avis que Matael, afin de ne pas tout mélanger même si les tags permettent de faire le tri. Pour moi ce dépôt était dédié aux *issues* qui ne dépendaient pas d'un projet en particulier (CA, questions, nouveaux projets, événements, ...).

Je trouve ce mode d'organisation personnellement plus pratique et moins fouillis. Par contre il faudrait mettre en avant cet onglet dont @Matael parle qui regroupe toutes les *issues* de tous les projets mais je ne l'ai pas trouvé. Modifier le README de ce dépôt en conséquence serait un bon point de clarification si on accepte donc de ranger les issues dans les dépôts des projets concernés avec un lien vers toutes les *issues* de tous les projets.

**Comment by jblb** [comment]
De ce que je me souvient, quand @Matael a proposer ce repo c’était bien pour y mettre toutes les issues qui n'étaient pas liées a un projet particulier ou pour les issues qui étaient transversales et qui concernaient touts les projets, par ex" améliorer la documentation des projets."

**Comment by neomilium** [comment]
Salut,
IMHO, nul besoin de prendre les gens pour des idiots, faisons les choses
correctement : les issues de projet sur les projets en question, les issues
internes, éventuellement généraliste, sur le dépôt internal. Pour un
nouveau venu, soit il connaît les bugs tracker et c'est gagné, soit il ne
connaît pas et il n'y va pas.

**Comment by neomilium** [comment]
Deux infos qui viennent compléter mon point de vue:
- si on veut une seule liste pour avoir une vue d'ensemble on utilise l'API
de github et on se fait ça en web dynamique 2.0 clicaconvi
- selon la méthode agile, on demande à celui qui se sert/va se servir de
outil pour décider ce qu'on implémente... Si c'est pour les nouveaux, il
faut choper un nouveau et lui demander :-) si c'est pour les contributeurs
actuels, demandons l'usage des actuels...

**Comment by MicroJoe** [comment]
> Si on veut une seule liste pour avoir une vue d'ensemble on utilise l'API de github et on se fait ça en web dynamique 2.0 clicaconvi

C'est une bonne idée, par contre on héberge ça où ? Si on arrive à tout faire en Javascript on peut mettre ça sur le site statique mais sinon si il y a du code côté serveur ça va être plus compliqué.

>  si c'est pour les contributeurs actuels, demandons l'usage des actuels

Clairement mon usage est celui que tu décris dans ta précédente réponse : à chaque projet ses bugs.

On ferme donc cette issue ?

**Comment by MicroJoe** [comment]
Voici le lien vers toutes les issues.

https://github.com/issues?user=haum

Je le rajouterai dans le README de ce dépôt, en attendant, je ferme.

**Comment by neomilium** [comment]
Bien joué :)

2015-07-07 17:31 GMT+02:00 Romain Porte <notifications@github.com>:

> Closed #47 <https://github.com/haum/haum_internal/issues/47>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haum/haum_internal/issues/47#event-349814703>.
>



-- 
Romuald
