### ISSUE TITLE
Rédiger un article sur le hack de la PCBlastifieuse

### ISSUE THREAD

**Issue by MicroJoe** [haum/haum_internal#48]
Pour les plus attentifs d'entre vous vous aurez remarqué que j'ai rédigé [une page](http://haum.org/pages/pcblastifieuse.html) décrivant le projet PCBlastifieuse.

Cependant cette page a pour seul but de présenter dans les grandes lignes le projet et ne montre pas toutes les étapes du hack alors que plein de photos sont disponibles pour expliquer tout ce que l'on à fait dessus.

Cette issue est donc un mémo personnel **mais aussi une demande de commentaires (RFC ?)** afin d'avoir votre avis concernant la rédaction d'un tel article qui explique point par point tout ce que l'on a pu faire sur la plastifieuse (mesures, capteurs, adaptateurs, passage de câbles, découpes, ...).

**Comment by jblb** [comment]
Romain Porte <notifications@github.com> a écrit :
(mesures, capteurs, adaptateurs, passage de câbles, découpes, ...).

moi je vote pour !

-- 
@+
jérôme

**Comment by Matael** [comment]
Effectivement, plus d'infos serait un bon moyen d'enseigner les rudiments de ce genre de hack.

Dans ce cas précis, je pense qu'une narration chronologique est clairement indiquée. L'objectif étant alors de montrer le sens de la démarche.

On peut aussi envisager un article de blog reprenant la chronologie du hack et sur la page du projet de simples informations sur les capteurs/actionneurs installés, et sur le choix logiciel qui a été réalisé pour l'arduino.

**Comment by MicroJoe** [comment]
C'est la philosophie que j'ai essayé d'appliquer à l'article : juste décrire comment ça fonctionne mais passer un peu sur comment tout a été réalisé.

Plus qu'à donc commencer à rédiger un brouillon qui retrace cet historique pendant que je l'ai encore en tête, avec les images du Flickr à l'appui.

**Comment by MicroJoe** [comment]
Done. http://haum.org/hack_pcblastifieuse.html
