### ISSUE TITLE
Détailler les procédures d'inscription aux différents services du HAUM

### ISSUE THREAD

**Issue by MicroJoe** [haum/haum_internal#49]
Bonjour,

Récemment on m'a ajouté à plein de services du HAUM, cependant je n'avais trouvé aucune piste sur le sujet permettant de savoir toutes les marches à suivre pour pouvoir bidouiller tel ou tel truc.

Voici donc une liste (non exhaustive) des différentes procédures qui seraient intéressantes à détailler pour les nouveaux arrivants/contributeurs ainsi que des débuts de solutions :

 - **Comment publier des images sur Flickr :** les envoyer sur la liste du bureau.
 - **Comment modifier/créer des projets Github du HAUM :** fork + pull request (ce que j'ai du faire au début) ou plus simple se faire ajouter au groupe Github `haum`.
 - **Comment participer au bugtracker haum_internal :** parce-que Github c'est un peu un truc de geek mais des membres non codeurs peuvent (doivent ?) utiliser ce bugtracker pour signaler des idées/problèmes (car j'ai l'impression que seuls ceux qui codent un peu au HAUM utilisent Github).
 - **Comment s'inscrire sur le wiki :** ??? (j'ai envie de déposer cette aide sur le wiki du HAUM en fait)
 - **Comment avoir l'autorisation pour faire un !updatesite sur IRC :** se faire ajouter dans la liste des utilisateurs autorisés par un admin ; TODO : expliquer ça également dans la réponse du bot au lieu de "on se connait ?".
 - **Comment pouvoir devenir un Twouitteur autorisé en utilisant Com`Bot :** ???

J'en oublie surement mais ça serait à mon avis d'une grande aide aux nouveaux et permettrai de booster un peu la participation.

Vos avis et autres entrées dans cette liste sont les bienvenus !

**Comment by jblb** [comment]
Romain Porte <notifications@github.com> a écrit :

> Récemment on m'a ajouté à plein de services du HAUM, cependant je  
> n'avais trouvé aucune piste sur le sujet permettant de savoir toutes  
> les marches à suivre pour pouvoir bidouiller tel ou tel truc.
Bien vu ! ceux qui on vu les les services arriver les connaissent mais  
les gens qui arrivent après n'ont effectivement pas de doc là dessus

>
> Voici donc une liste (non exhaustive) des différentes procédures qui  
> seraient intéressantes à détailler pour les nouveaux  
> arrivants/contributeurs ainsi que des débuts de solutions :
>
>  - **Comment publier des images :** les envoyer sur la liste du bureau.
ou demander le mot de pass du compte

>  - **Comment modifier/créer des projets Github du HAUM :** fork +  
> pull request (ce que j'ai du faire au début) ou plus simple se faire  
> ajouter au groupe Github `haum`.
ce se faire ajouter au groupe Github `haum` est certainement la  
meilleur solution

>  - **Comment participer au bugtracker haum_internal :** parce-que  
> Github c'est un peu un truc de geek mais des membres non codeurs  
> peuvent (doivent ?) utiliser ce bugtracker pour signaler des  
> idées/problèmes (car j'ai l'impression que seuls ceux qui codent un  
> peu au HAUM utilisent Github).
là je ne sais pas, réfléchissons ensemble comment faire avancer ce truc

>  - **Comment s'inscrire sur le wiki :** ??? (j'ai envie de déposer  
> cette aide sur le wiki du HAUM en fait)
envoyer ta clef ssh a quelqu'un qui a accès au serveur et lui demander  
de te créer un compte. Peut être qu'il faut faire une page de wiki  
pour maintenir une liste des gens qui on accès au serveur carbon.

>  - **Comment avoir l'autorisation pour faire un !updatesite sur IRC  
> :** se faire ajouter dans la liste des utilisateurs autorisés par un  
> admin ; TODO : expliquer ça également dans la réponse du bot au lieu  
> de "on se connait ?".
>  - **Comment pouvoir devenir un Twouitteur autorisé en utilisant  
> Com`Bot :** ???
Faire trente six courbettes @matael* et espérer qu'il n'ai pas casser  
la base de données :)

* c'est a dire le pinger sur irc

-- 
@+
jérôme

**Comment by Matael** [comment]
Le vendredi 03 juil. 2015 à 09:31:15 (-0700), JbLb a écrit :
> Romain Porte <notifications@github.com> a écrit :
> 
> > Récemment on m'a ajouté à plein de services du HAUM, cependant je  
> > n'avais trouvé aucune piste sur le sujet permettant de savoir toutes  
> > les marches à suivre pour pouvoir bidouiller tel ou tel truc.
> Bien vu ! ceux qui on vu les les services arriver les connaissent mais  
> les gens qui arrivent après n'ont effectivement pas de doc là dessus

C'est effectivement une excellente idée. Eventuellement, il faudrait en
causer avec @FredBlain qui peut certainement aider autant que moi là
dessus.

> >  - **Comment avoir l'autorisation pour faire un !updatesite sur IRC  
> > :** se faire ajouter dans la liste des utilisateurs autorisés par un  
> > admin ; TODO : expliquer ça également dans la réponse du bot au lieu  
> > de "on se connait ?".
> >  - **Comment pouvoir devenir un Twouitteur autorisé en utilisant  
> > Com`Bot :** ???
> Faire trente six courbettes @matael* et espérer qu'il n'ai pas casser  
> la base de données :)
> 

Ça fait longtemps que j'ai pas réellement flingué la DB :) Par contre,
je préfère qu'on ajoute pas les gens en DB à tour de bras. Il est
toujours possible de proposer un tweet sur IRC et qu'une personne ayant
les droits l'envoie. Sinon effectivent il suffit de se faire ajouter aux
listes de Com`bot ou de Twaum (pour respectivement le site/l'agenda et
le twitter).

**Comment by MicroJoe** [comment]
Done, n'hésitez pas à modifier la page de wiki que je viens de créer : https://wiki.haum.org/doku.php?id=services_haum

**Comment by jblb** [comment]
Romain Porte <notifications@github.com> a écrit :

> Done, n'hésitez pas à modifier la page de wiki que je viens de créer  
> : https://wiki.haum.org/doku.php?id=services_haum

j'ai complété la liste de ceux qui peuvent créer un compte utilisateur  
sur carbon

-- 
@+
jérôme
