### ISSUE TITLE
Lien vers le wiki

### ISSUE THREAD

**Issue by jblb** [haum/haum_internal#50]
je viens de me rendre compte que sur le site il n'y avais pas de lien vers notre wiki. Est ce que l'on doit en mettre un ? si oui comment on intègre ça dans le site ?

**Comment by MicroJoe** [comment]
Peut-être sur la droite comme les liens vers les autres sites ?

**Comment by Matael** [comment]
Je pense qu'avoir un lien dans la partie "hackerland" du site peut être intéressant, mais à mon avis, il ne faut pas le mettre directement dans la barre de droite.

**Comment by MicroJoe** [comment]
Étant donné que le wiki est plus pour les membres que pour le public, :+1:.

**Comment by jblb** [comment]
un lien dans la partie "hackerland" du site me plaît bien

**Comment by Matael** [comment]
Fixed in haum/website-content@b6c094b
