### ISSUE TITLE
Un générateur de phrases pour l'agenda

### ISSUE THREAD

**Issue by MicroJoe** [haum/haum_internal#52]
Quand [on regarde l'agenda](http://haum.org/pages/agenda.html) on remarque que les descriptions des séances sont répétitives (en plus d'être ajouté à la main sur IRC).

Il pourrait être intéressant de modifier le bot ou d'en créer un nouveau au choix qui prend une phrase dans une liste de possibilités de manière plus ou moins aléatoire (phrase différente d'une séance sur l'autre, etc.) pour reprendre ce que faisait pendant un moment @fredblain en utilisant des phrases rigolotes et différentes pour chaque séance.

**Comment by rebrec** [comment]
J'ai effectué des modifications sur https://github.com/haum/combot/blob/master/Combot.pm :
- $self->{agenda_messages} contient la liste des phrases qu'il va falloir alimenter, n'étant pas très créatif, je laisserais ceux qui le souhaitent alimenter et corriger les 4 phrases que j'ai mis en exemple.
- Une commande `!agenda add_seance JJ/MM/AAA [h]h:mm` qui va choisir une phrase aléatoirement dans le tableau agenda_messages et faire un `!agenda add_seance JJ/MM /AAA[h]h:mm` "Session Bidouilles" "Local du Haum" $message_random

J'espère bien avoir compris le besoin que tu as formulé.
Je constate que le bot est aussi responsable des messages twitter d'annonce de l'ouverture et de la fermure du hackerspace. Je ne sais pas s'il faut aussi apporter un message aléatoire à cette fonctionnalité.

**Comment by matael** [comment]
Merci beaucoup @rebrec !

J'ai corrigé les phrases que tu as proposé et j'en ai rajouté quelques unes.

On pourrait effectivement prévoir des trucs aléatoires pour la fermeture et l'ouverture.

PS: en tapant ce message, j'ai fermé 3 fois ce p****n d'onglet FF simplement parce que dans ce logiciel, ^W n'est pas lié a "supprime le mot précédent"...

**Comment by gagath** [comment]
Sinon tu peux installer un plugin qui permet de te lancer Vim pour éditer dans des `<textarea>` @Matael (je connais Vimperator mais il doit y en avoir d'autres).

Je ferme car la fonctionnalité a bien été implémentée, merci @rebrec !
