### ISSUE TITLE
Supprimer le guide PCB sur le wiki

### ISSUE THREAD

**Issue by MicroJoe** [haum/haum_internal#53]
Parce-que on en a un plus joli et plus complet maintenant ; il faut juste que les comptes sur le wiki soient réactivés pour pouvoir supprimer la page.

Si les comptes sont déjà réactivés, c'est que j'ai perdu mon mot de passe car je ne parviens pas à me connecter au wiki.

**Comment by gagath** [comment]
Fait : https://wiki.haum.org/doku.php?id=guide_pcb
