### ISSUE TITLE
Vérifier le fonctionnement du bouton d'ouverture du haum sur la box.

### ISSUE THREAD

**Issue by matael** [haum/haum_internal#55]

**Comment by neomilium** [comment]
Y-a-t il eu un problème avec celui-ci pour demander une vérification ?

2016-01-09 19:32 GMT+01:00 Mathieu G. notifications@github.com:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/haum/haum_internal/issues/55.

## 

Romuald

**Comment by matael** [comment]
De fait.

Je n'ai réussi ni a ouvrir ni à fermer le HAUM vendredi.

**Comment by jblb** [comment]
Bonjour,

**Comment by matael** [comment]
Le bouton est parfaitement fonctionnel, le paramètrage est simplement différent du paramétrage précédent. Là, le ACK (avec la led qui passe au bleu) n'est disponible qu'après relachement du bouton alors qu'auparavant, c'était disponible même lorsqu'il était encore appuyé.

Je laisse la nouvelle config et je ferme l'issue.

**Comment by neomilium** [comment]
Pour info, le bouton n'est jamais passé au bleu avant de relâcher, la
configuration n'a pas été changée.
