### ISSUE TITLE
HMS: erreur sur option silent 

### ISSUE THREAD

**Issue by JackDesBwa** [haum/haum_internal#57]
Lorsque "silent" est mal orthographié, il n'y a pas d'erreur.
Le mode silent est ignoré et donc il y a publication de message

**Comment by gagath** [comment]
Plop,

Cette erreur est liée à l'ancienne gestion de l'état du local. Maintenant que HMS gère effectivement l'ouverture à la place de Combot ce bug n'existe plus ; je ferme.
