### ISSUE TITLE
Renommer "talks" en "events" pour une meilleure communication externe

### ISSUE THREAD

**Issue by fredblain** [haum/haum_internal#8]
L'idée serait de renommer les "talks" en "events" de sorte de regrouper toutes les manifestations organisées et/ou auxquelles le HAUM participe(ra).
Ainsi nous pourrions avec un "events.haum.org" lister les confs, mais également les sessions pédagogiques sur Arduino, et autres futurs events au même endroits.
Et lorsqu'une manifestation est organisée conjointement avec un partenaire, ce dernier aura une page à laquelle faire référence dans sa comm', une page identifiée HAUM. Ce qui est actuellement le cas avec LaRucheNumérique pour son agenda sur la conf #opendata.

Qu'en pensez-vous ? J'attends vos retours.

**Comment by matael** [comment]
Compte tenu de la nouvelle organisation et du fait que le site ait été fermé il y a plus d'un an, je clos l'issue.
