### ISSUE TITLE
Résoudre le problème de l'entrainement du Z qui "danse"

### ISSUE THREAD

**Issue by Matael** [haum/haum_internal#9]
Retenter avec une tige filetée neuve (en inox, bien droite) et passer au
tour chez Jblb

Si on y arrive pas avec les outils de jblb, l'idéal serait d'accéder à un
tour qui permet de faire deux épaulements sur la tige filetée en conservant
le centre de la tige filetée durant l'usinage.

**Comment by jblb** [comment]
la cause est identifiée elle viens de mon tour et de la façon dont à été usinée la pièce. Comme ce problème de concentricité  se reproduira lors de d'autres usinage j'ai fait l’acquisition de pinces de précision pour pouvoir faire ce genre d'usinage. Il suffira de racheter une tige filetée inox et de refaire les usinages.

**Comment by neomilium** [comment]
@jblb cette issue a été déplacée pour être dans le bon projet : https://github.com/haum/axihaum/issues/1
Merci de faire les commentaires afférant au bon endroit :)

**Comment by jblb** [comment]
houps :( c'est corrigé https://github.com/haum/axihaum/issues/1#issuecomment-120537528
